### ISSUE TITLE
Add bulk_create_returning

### ISSUE THREAD

**Issue by frenzyk** [M1hacka/django-pg-returning#13]
When you, for example, using F() or passing datetime TZ aware string to DB - you don't know resulting values and have to make an additional SELECT call without RETURNING feature

**Comment by M1ha-Shvn** [comment]
I've tried digging into the case, and found out, that django gives no ability to use function in insert statements, raising error:

> Error: Failed to insert expression "Coalesce(Col(tests_testmodel, tests.TestModel.int_field), Value(1))" on tests.TestModel.int_field. F() expressions can only be used to update, not to insert.

**Comment by M1ha-Shvn** [comment]
Released 1.2.0
